---
- name: create /etc/contrail/analytics_snmp
  file:
    path: /etc/contrail/analytics_snmp
    state: directory
    recurse: yes

- name: update contrail-snmp-collector and contrail-analytics-snmp-topology image
  shell: "docker pull {{ container_registry }}/{{ item }}:{{ contrail_version_tag }}"
  with_items:
    - "{{ contrail_container_prefix }}-node-init"
    - "{{ contrail_container_prefix }}-nodemgr"
    - "{{ contrail_container_prefix }}-analytics-snmp-topology"
    - "{{ contrail_container_prefix }}-analytics-snmp-collector"

- name: create contrail analytics_snmp docker-compose file
  template:
    src: contrail-analytics-snmp.yaml.j2
    dest: /etc/contrail/analytics_snmp/docker-compose.yaml

- name: start contrail analytics_snmp
  docker_service:
    project_src: /etc/contrail/analytics_snmp
